---
blank_issues_enabled: false
contact_links:
- name: Suggestions
  url: https://github.com/Love-and-Tolerance/Love-and-Tolerance/discussions
  about: Please create a new discussion (under category "ideas")
